### ISSUE TITLE
Could this repo also be used for Windows, OS X, ... dependencies?

### ISSUE THREAD

**Issue by julianrendell** [alicevision/AliceVisionDependencies#9]
This approach that you're using for Travis builds makes a lot of sense.

Could it be extended for other OSes?

Would you be willing to have something similar for Meshroom?

**Comment by simogasp** [comment]
Hardly.
This is fine for travis but it is very hard to maintain and not so straightforward to use.
Switching to vcpkg would be a better choice as it can support all three major OS 
and you can better manage the dependencies. 
We are not far from having official ports for popsift (https://github.com/microsoft/vcpkg/pull/10979) and cctag (https://github.com/alicevision/vcpkg/tree/ports/cctag), if we add alicevision then you can almost fully automate the deployment process of meshroom as well.

**Comment by julianrendell** [comment]
That's a better way forward!

However I'm finding vcpkg to be frustrating; not as reliable/full featured as apt/homebrew (maybe even nuget - have less experience with that.)

E.g. I told it to install QT[latest]... (=>QT5.14.2) and when I ask it to list installed packages, it reports 5.12 is installed. I think that's because this is the "default" version reported in the control file.

I also quickly looked at how to "pin" a port version. Looks like there is no way- you have to checkout the entire VCPKG repo, including the vcpkg scripts @ the revision of the version you want. If you want to pin several library versions, I guess you're down to manually checking out certain sets of files at specific revisions. Pinned versions don't always work great, but for me they've worked more often than not, and much easier to manage than (potentially) having to create multiple build environments/special-case scripts to get a specific combo of library versions.

This is likely lack of knowledge; but I'm wondering how you'd say build a Meshroom release against say the latest QT, but specific versions of ctags + AliceVision with vcpkg (when they're all at different revision levels of the main vcpkg repo.)

**Comment by julianrendell** [comment]
Oh, I just remembered BSD package systems often call this an overlay...

Bingo! https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md
This is not the easiest for a newb to find- but there's an overlay option listed in the command help when it's run.

This makes things a *lot* simper!

For CI speed/simplicity/de-coupling from the entire VCPKG repo, would you consider creating a github repo that's a VCPKG overlay that could be pulled into a vanilla VCPKG install?

Closing this, and watching the items you linked.
